version: '3'

tasks:
  satellite:
#    deps:
#      - nats:satellite
    cmds:
      - ts-node handlers/satellite/satellite.ts
  main:
#    deps:
#      - nats:main
    cmds:
      - ts-node handlers/main/main.ts
  satellite-cmd:
#    deps:
#      - nats:satellite
    cmds:
      - ts-node handlers/satellite/satellite-commands.ts
  main-cmd:
#    deps:
#      - nats:main
    cmds:
      - ts-node handlers/main/main-commands.ts
  leaf:
#    deps:
#      - nats:main
    cmds:
      - ts-node handlers/leaf/leaf.ts
  nats:main:
    run: once
    cmds:
      - docker compose --profile main up -d --wait
  nats-*:
    run: once
    cmds:
      - docker compose --profile * up  -d --wait
  nats:satellite:
    run: once
    cmds:
      - docker compose --profile satellite up -d --wait
  nats:all:
    run: once
    cmds:
      - docker compose --profile "*" up -d --wait
  nats:destroy:
    - docker compose --profile "*" down

  reply:
    cmds:
      - ts-node handlers/reply.ts

  request:
    cmds:
      - ts-node handlers/request.ts

  bench-reply:
    deps:
      - nats:all
    cmds:
      - nats bench foo --sub 1 --reply --server nats://localhost:4322

  bench-request:
    deps:
      - nats:all
    cmds:
      - nats bench foo --pub 1 --request --msgs 10000 --server nats://localhost:4223,nats://localhost:4224,nats://localhost:4225

  bench-pub:
    deps:
      - nats:all
    cmds:
      - nats bench --js --purge foo --size 1000 --msgs 1000000 --pub 1 --server nats://localhost:4322,nats://localhost:4323,nats://localhost:4324

  bench-sub:
    deps:
      - nats:all
    cmds:
      - nats bench --js --purge foo --sub 5 --msgs 1000000 --server nats://localhost:4223,nats://localhost:4224,nats://localhost:4225


  configure-gw:
    cmds:
      - ts-node handlers/gw-streams/configure/configure-to-main.ts
      - ts-node handlers/gw-streams/configure/configure-from-main.ts

  reinit:
    cmds:
      - task: nats:destroy
      - task: nats:all
      - task: configure-gw

  main.streams.sub:
    - ts-node handlers/gw-streams/subscriber.main.ts
  main.streams.pub:
    - ts-node handlers/gw-streams/emitter.main.ts

  main.sub:
    - ts-node handlers/gw-pub-sub/subscriber.main.ts
  main.pub:
    - ts-node handlers/gw-pub-sub/emitter.main.ts

  main.reply:
    - ts-node handlers/gw-pub-sub/replier.main.ts
  main.req:
    - ts-node handlers/gw-pub-sub/requester.main.ts

  ###############
  #### AGENT ####
  ###############
  agent.streams.sub:
    - ts-node handlers/gw-streams/subscriber.agent.ts
  agent.streams.pub:
    - ts-node handlers/gw-streams/emitter.agent.ts

  agent.sub:
    - ts-node handlers/gw-pub-sub/subscriber.agent.ts
  agent.pub:
    - ts-node handlers/gw-pub-sub/emitter.agent.ts

  agent.reply:
    - ts-node handlers/gw-pub-sub/replier.agent.ts
  agent.req:
    - ts-node handlers/gw-pub-sub/requester.agent.ts
