version: '3'

tasks:
  leaf:
    deps:
      - nats
    cmds:
      - ts-node handlers/leaf.ts
  main:
    deps:
      - nats
    cmds:
      - ts-node handlers/main.ts
  nats:
    run: once
    cmds:
      - docker compose up -d --wait
  nats:destroy:
    - docker compose down

  reply:
    cmds:
      - ts-node handlers/reply.ts

  request:
    cmds:
      - ts-node handlers/request.ts

  bench-reply:
    deps:
      - nats
    cmds:
      - nats bench foo --sub 1 --reply --server nats://localhost:4222

  bench-request:
    deps:
      - nats
    cmds:
      - nats bench foo --pub 1 --request --msgs 10000 --server nats://localhost:4223
